### ISSUE TITLE
xterm functionality of terminal-light doesn't work in urxvt after version 9.25

### ISSUE THREAD

**Issue by pseyfert** [Canop/terminal-light#2]
I use a light terminal and noticed broot applies its dark theme instead of the light theme (I use urxvt 9.30 writing black on white).

going down the rabbit hole, `cargo run` from the `terminal-light` crate prints `Error: Unsupported` for me. I think I traced it down by now to the release notes http://lists.schmorp.de/pipermail/rxvt-unicode/2021q2/002606.html which say

> ESC G (query rxvt graphics mode) has been disabled due to security
          implications. The rxvt graphics mode was removed in rxvt-unicode 1.5,
          and no programs relying on being able to query the mode are known.

i reverted to urxvt 9.22 (ubuntu 20.04 and debian stable) and there terminal-light works (afaiu thanks to the `query_bg_color` function in `xterm.rs`)

On top of that, the COLORFGBG detection fails for me because of its value `COLORFGBG=0;default;15` the `default` can't be parsed to `u8`. (Not sure yet if that's something I should change anyway and where that gets set…)

**Comment by Canop** [comment]
> On top of that, the COLORFGBG detection fails for me because of its value `COLORFGBG=0;default;15` the `default` can't be parsed to `u8`. (Not sure yet if that's something I should change anyway and where that gets set…)

What is supposed to be that "default" ? A problem is I never found any authoritative definition of that variable. If you'd find some it would be helpful.

**Comment by Canop** [comment]
Found [this code](https://github.com/rocky/shell-term-background/blob/master/term-background.bash#L89) which parses de `;default` part. That doesn't really make it a standard... What disturbs me is that if there's a new third component, it can certainly be something else than `"default"`, right ?

**Comment by Canop** [comment]
@pseyfert can you please check this PR solves the problem for you ?
https://github.com/Canop/terminal-light/pull/3

**Comment by pseyfert** [comment]
Hi, I also haven't figured out what `default` is meant to be / where I set it (not to mention why i chose to set it that way).

Your PR works for me. terminal-light does not report an error anymore and broot picks the correct theme now.

**Comment by Canop** [comment]
FYI broot 1.20 has just been released with terminal-light updated
