### ISSUE TITLE
Query timeout not sufficient for iterm2

### ISSUE THREAD

**Issue by zeenix** [Canop/terminal-light#4]
I have been having [a strange issue](https://github.com/zeenix/gimoji/issues/69) in my `gimoji` project where strange characters get entered on the search bar after the launch. [Turns out](https://github.com/zeenix/gimoji/issues/69#issuecomment-1890769337) it's because of the timeout on dynamic detection terminal-light does, not being sufficient for iterm2. While bumping of this timeout will [likely not be a good solution](https://github.com/zeenix/gimoji/issues/69#issuecomment-1890990119) for gimoji project, I thought I should still report this so you may be able to solve it for others.

**Comment by Canop** [comment]
Thanks for the report, I'll look into it (may take a while, I have a huge backlog).

**Comment by zeenix** [comment]
@Canop no worries. [Turns out](https://github.com/zeenix/gimoji/issues/69#issuecomment-1891003664) the problem might be actually in your `xterm-query` crate. Feel free to move the issue to that repo, if that's the case indeed.

**Comment by Canop** [comment]
The issue is fine in this repo. I suspect it's a documentation problem regarding the raw terminal mode.

**Comment by Canop** [comment]
The diagnostic doesn't seem correct: terminal_light does switch to raw mode. See https://github.com/Canop/terminal-light/blob/main/src/xterm.rs#L5

As terminal-light's crossterm dependency just got bumped from 0.23 to 0.27, it's possible the problem got away as crossterm changed a lot between those versions.

**Comment by zeenix** [comment]
> The diagnostic doesn't seem correct: terminal_light does switch to raw mode.

You're referring to an obsolete diagnostic (since it was more of a guess). If you read [the next comment ](https://github.com/zeenix/gimoji/issues/69#issuecomment-1891003664) from @kdheepak, you'll notice that they looked at the code and realized that.

> As terminal-light's crossterm dependency just got bumped from 0.23 to 0.27, it's possible the problem got away as crossterm changed a lot between those versions.

Thanks for letting me know. I will check on my mac later today.

**Comment by zeenix** [comment]
> Thanks for letting me know. I will check on my mac later today.

Actually, since terminal-light's latest release already has this change, gimoji already bumped to the latest release so there was no need for fresh testing after all, but I still tested and I can still reproduce the issue.

So the problem has not solved itself. :(

**Comment by Canop** [comment]
Do you have a minimal reproduction case, not involving a whole external program ? Is the problem only on MacOS X ?

**Comment by zeenix** [comment]
> Do you have a minimal reproduction case, not involving a whole external program?

Not yet but I can try to create one. FWIW [gimoji](https://github.com/zeenix/gimoji/issues/69) is quite a simple app though and you might like to use it yourself. :wink: 

> Is the problem only on MacOS X ?

Yes, AFAIK. I have only run gimoji on Linux and MacOs though. 

Also the only way I know to reproduce this issue is launching gimoji through a commit hook (which is also the usual way to launch it).

**Comment by zeenix** [comment]
> > Do you have a minimal reproduction case, not involving a whole external program?
> 
> Not yet but I can try to create one. FWIW [gimoji](https://github.com/zeenix/gimoji/issues/69) is quite a simple app though and you might like to use it yourself. 😉

I mean it's as simple as an app can get:

```
❯ wc -l src/*.rs
   25 src/colors.rs
   34 src/emoji.rs
  225 src/main.rs
   63 src/search_entry.rs
  112 src/selection_view.rs
   56 src/terminal.rs
  515 total
```

**Comment by Canop** [comment]
I installed gimoji, but I'm not sure there's a way to reproduce the problem on linux.
If needed, we can discuss at https://miaou.dystroy.org/3768

**Comment by zeenix** [comment]
> I installed gimoji,

:+1: 

> but I'm not sure there's a way to reproduce the problem on linux.

I just remembered that this used to happen on Linux too before I added this

```
exec < /dev/tty
```

to the git commit hook. So I just editted `.git/hooks/prepare-commit-msg` (I had the hook already installed using `gimoji -i`) and removed that line and was able to reproduce the issue using `git commit -a` or even `git commit --amend`. I hope the same method works for you.

I never understood why this line helps on Linux but unfortunately on Mac, it doesn't help. However, if we read @kdheepak's observations, it is likely just coincidental.

> If needed, we can discuss at https://miaou.dystroy.org/3768

I joined but it didn't work for me. I just saw blank screens and couldn't even see my own messages.

**Comment by Canop** [comment]
The problem is related to the way git controls the exectutable it launches. I'm even surprised it works on linux as it relies on git willingly relaying TTY in both directions.

**Comment by zeenix** [comment]
> The problem is related to the way git controls the exectutable it launches.

I'm not very surprised. Thanks for looking into it.

> I'm even surprised it works on linux as it relies on git willingly relaying TTY in both directions.

Shouldn't it? :thinking:

**Comment by zeenix** [comment]
> > I'm even surprised it works on linux as it relies on git willingly relaying TTY in both directions.
> 
> Shouldn't it? 🤔

I mean should git not relay TTY for its hook scripts?

Also to keep in mind that the issue goes away if we don't call `terminal_light::luma` so it's not git alone.

**Comment by zeenix** [comment]
@Canop I would suggest taking advantage of findings of @kdheepak that they shared in the [gimoji issue](https://github.com/zeenix/gimoji/issues/69). They [tracked down the issue to xterm-query](https://github.com/zeenix/gimoji/issues/69#issuecomment-1891003664).

**Comment by Canop** [comment]
The point isn't here. Look for "git hook ansi escape sequence" and similar. You'll see git isn't supposed to be compatible with them, so all applications which use them have the same problem when called in git hooks. The `exec < /dev/tty` hack seems to allow the application to circumvent git (I guess to receive the input) but this looks really brittle.
A proper solution would probably be to call terminal-light in a different workflow (I don't know if there's something dedicated in git hook system for that), or to use env variables.

**Comment by zeenix** [comment]
> The point isn't here. Look for "git hook ansi escape sequence" and similar. You'll see git isn't supposed to be compatible with them, so all applications which use them have the same problem when called in git hooks. The `exec < /dev/tty` hack seems to allow the application to circumvent git (I guess to receive the input) but this looks really brittle.

Right. Thanks for looking into this again.

> A proper solution would probably be to call terminal-light in a different workflow (I don't know if there's something dedicated in git hook system for that), or to use env variables.

Yeah, I guess I've to bite the bullet and remove auto-detection and just provide easy options (cli and env) to specify the luma.

**Comment by zeenix** [comment]
So I had a chat with Lennart Poettering (of the systemd fame) about this and he informed me that the `exec < /dev/tty` is right on the money as you can't assume your stdin to be tty (which is what you also wrote above) but he suggested that this should be done in the app itself. So I decided to dig a little deeper and found out that there are 2 very different issues (with the same symptoms) here on Linux and Mac:

* On Linux, gimoji was actually getting a "Unsupported platform" error but gimoji ignores it, which results in the query response still in the stdin buffer. I modified xterm-query to explicitly use `/dev/tty` as stdin and it fixed the issue. This would be also why `exec < /dev/tty` line in the hook script helped.
* On Mac, there is no error, which leads me to believe that the issue on the Mac is not related to whether or not stdin is tty. This would explain why the `exec < /dev/tty` line in the git hook did not help (like it does on Linux). This could be something specific to xterm though, not Mac. I've to dig deeper to figure this one out.

In any case, I think it would make sense for xterm-query to read from `/dev/tty` always, so I submitted [a PR](https://github.com/Canop/xterm-query/pull/1) for that.

**Comment by Canop** [comment]
> In any case, I think it would make sense for xterm-query to read from /dev/tty always, so I submitted https://github.com/Canop/xterm-query/pull/1 for that.

Indeed. I'll have to try and check things but you might be right!

(I don't think this would fix bugs in current use cases of xterm-query or terminal-light, but it looks cleaner)

**Comment by zeenix** [comment]
@Canop thanks so much for merging my PR and releasing. Things are fixed on Linux now.

As for Mac, I think I know the problem: [mio doesn't support polling from /dev/tty](https://github.com/tokio-rs/mio/issues/1377). I'll see what can be done for it but if you have any ideas, please do let me know.

**Comment by ku1ik** [comment]
@zeenix I had to deal with that mio issue in asciinema recently, ended up rewriting this part using `pselect`, which works fine on both Linux and macOS: https://github.com/asciinema/asciinema/commit/a29aa7665f0d61ff71400d3fd617d7b78df79352

**Comment by zeenix** [comment]
> @zeenix I had to deal with that mio issue in asciinema recently, ended up rewriting this part using `pselect`, which works fine on both Linux and macOS: [asciinema/asciinema@a29aa76](https://github.com/asciinema/asciinema/commit/a29aa7665f0d61ff71400d3fd617d7b78df79352)

Thanks for sharing. I think `pselect` has the same limitation as `select`, which is why [we chose to only use `select` for Mac](https://github.com/Canop/xterm-query/pull/4/files).
