### ISSUE TITLE
Response is not consumed entirely in VSCode

### ISSUE THREAD

**Issue by tautropfli** [Canop/terminal-light#5]
When calling `background_color` or `luma` from the embedded terminal in VSCode
part of the terminal's response remains unread in stdin, namely `ESC \`.

This can be observed as follows (press CTRL-C to exit):
```
sh-5.2$ cargo run --example dark-or-light && cat -v
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 0.01s
     Running `target/debug/examples/dark-or-light`

 You're using a light theme (luma=0.96875)

^[\
```

Notes:
* The `-v` option of cat makes it so that control characters are printed using caret notation. \
  `^[` = U+001B (Escape)
* `ESC \` is the "String Terminator" control character which can be used to terminate OSC queries instead of BEL.

<sub>I'm the author of [terminal-colorsaurus](https://github.com/bash/terminal-colorsaurus) - a "competing" library ^^</sub>

**Comment by Canop** [comment]
> I'm the author of [terminal-colorsaurus](https://github.com/bash/terminal-colorsaurus) - a "competing" library ^^

Great, so you're competent to have a look at what doesn't work here :-)

**Comment by tautropfli** [comment]
Dang it, I should not have mentioned that :))

<sub>Ok, ok, I'll add it to my to-do list</sub>

**Comment by Canop** [comment]
This should be fixed with https://github.com/Canop/terminal-light/pull/6

The problem was that vscode flushes before sending the OSC sequence terminator, something I didn't think would happen.

Thanks a lot for your precise bug report
